name: github-page-ci-cd

on:
  push:
    tags:
      # 레포지토리에 아래 패턴과 일치하는 태그가 생성될 때 아래 jobs 들이 진행됩니다.
      # 아래 예시같은 경우 레포지토리에 github-page-v0.0.1 라는 태그가 생성되면 트리거가 발동합니다.
      - "github-page-v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      # 정적 웹사이트 배포를 위한 빌드 과정을 작성하면 됩니다.
      # 아래는 그 예시 입니다.
      # - run: yarn install
      # - run: yarn build
      # - run: or more...

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
        	# 빌드 결과물이 생성되는 경로를 작성해줍니다. 
        	# 여기에서는 예시로 yarn build 명령어를 입력하면 빌드 결과물이 ./build 에 생성된다고 가정하였습니다.
        	# 즉, 만약 빌드 결과물이 ./out/build 에 생성된다면 아래 path 를 "./out/build" 로 수정하면 됩니다.
          path: "./build" 

  github-page-deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy Github Pages
        uses: actions/deploy-pages@v4
